// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportClubFaratechno.Models.SportClubFaratechnoDB;

namespace SportClubFaratechno.Migrations
{
    [DbContext(typeof(SportClubFaratechnoDBContext))]
    [Migration("20220126033401_SportClub_39")]
    partial class SportClub_39
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.Access", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionDateShamsi")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebApiAddress")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Access");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.AppRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<double>("Credit")
                        .HasColumnType("REAL");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LandlineNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("MobileNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.BuffetDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BuffetId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BuffetItem")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionDateShamsi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BuffetDetail");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.BuffetItemTypeItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BuffetItemId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BuffetItemTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BuffetItemTypeItem");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.Cabinet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CabinetName")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CabinetType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsEngaged")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cabinet");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.Club", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<long>("ClubId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Club");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.ClubCabinet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CabinetId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ClubId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ClubCabinet");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.ClubSalon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ClubId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SalonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ClubSalon");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.DetailType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailValue")
                        .HasColumnType("TEXT");

                    b.Property<long?>("MasterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionDateShamsi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DetailType");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.Invoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionDateShamsi")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.MasterType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionDateShamsi")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MasterType");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.RoleAccess", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccessId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionDateShamsi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoleAccess");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.SalonBuffet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BuffetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripiton")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SalonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionDateShamsi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SalonBuffet");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.SalonCabinet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CabinetId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SalonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionDateShamsi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SalonCabinet");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.SalonEquipment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Equipment")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsFreeToUse")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SalonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SalonEquipment");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.SalonSport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desctiption")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("SalonCabinetPrioraty")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SalonTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SportTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionDateShamsi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SalonSport");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.Session", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AtAprice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndDateShamsi")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumberOfPeople")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumberOfSessions")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SalonSportId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Sex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartDateShamsi")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<long?>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionDateShamsi")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.SessionDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SessionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionDateShamsi")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionDateShamsi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SessionDetail");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.SessionUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionDateShamsi")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SessionUser");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.SessionUserExerciseProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExcerciseProgram")
                        .HasColumnType("TEXT")
                        .HasMaxLength(3000);

                    b.Property<long>("SessionUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionDateShamsi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SessionUserExerciseProgram");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.SessionUserExtraDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SessionUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UserExtraDetailId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SessionUserExtraDetail");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.SessionUserTraffic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EntranceDatetime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntranceDatetimeShamsi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExitDatetime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExitDatetimeShamsi")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SessionUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionDateShamsi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SessionUserTraffic");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncomeSpend")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionDateShamsi")
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<long?>("TrnSource")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TrnType")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.UserAccess", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccessId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasAccess")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionDateShamsi")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserAccess");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.UserCabinet", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CabinetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionDateShamsi")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserCabinet");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.UserEquimentUsage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SalonEquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionDateShamsi")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("TimeOfUsage")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserEquimentUsage");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.UserExtraDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionDateShamsi")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserExtraDetail");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.UserExtraInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionDateShamsi")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserExtraInfo");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.SportClubFaratechnoDB.UserInsurance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionDateShamsi")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserInsurance");
                });

            modelBuilder.Entity("SportClubFaratechno.Models.TrafficCabinet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CabinetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionDateShamsi")
                        .HasColumnType("TEXT");

                    b.Property<long>("TrafficId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TrafficCabinet");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("SportClubFaratechno.Models.SportClubFaratechnoDB.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("SportClubFaratechno.Models.SportClubFaratechnoDB.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("SportClubFaratechno.Models.SportClubFaratechnoDB.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("SportClubFaratechno.Models.SportClubFaratechnoDB.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportClubFaratechno.Models.SportClubFaratechnoDB.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("SportClubFaratechno.Models.SportClubFaratechnoDB.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
